# configuration for https://github.com/MarcoIeni/release-plz

[workspace]
allow_dirty = true
changelog_config = "cliff.toml"
changelog_update = true
dependencies_update = true
git_release_enable = false
git_tag_enable = true
pr_labels = ["release"]
publish_allow_dirty = true
semver_check = false
